refactor: added a few brackets

diff --git a/.local/bin/workspace b/.local/bin/workspace
--- a/.local/bin/workspace
+++ b/.local/bin/workspace
@@ -1,7 +1,7 @@
 #!/bin/env bash
 
 __curr_workspace="$(hyprctl activeworkspace -j | jq '.["id"]')"
-__max_hypr_workspaces="$([ -z "$MAX_HYPR_WORKSPACES" ] && echo 0 || echo "$MAX_HYPR_WORKSPACES")"
+__max_hypr_workspaces="${MAX_HYPR_WORKSPACES:-"0"}"
 
 function usage {
  echo "Usage: workspace [OPTIONS]"
@@ -12,19 +12,19 @@ function usage {
  echo " -p, --prev      Previous workspace"
  echo " -m, --move      Move current window to next/previous workspace specified by --next or --prev" 
  echo ""
- echo '$MAX_HYPR_WORKSPACES can be used to set the maximum number of workspaces. If it is set to 0, control is handed over to hyprland'
+ echo "\$MAX_HYPR_WORKSPACES can be used to set the maximum number of workspaces. If it is set to 0, control is handed over to hyprland"
 }
 
 function handle_options {
-  if [ $# = 0 ]; then
+  if [ "$#" = 0 ]; then
     echo "error: atleast one option must be specified" >&2
     echo ""
     usage
     exit 1
   fi 
   
-  while [ $# -gt 0 ]; do
-    case $1 in
+  while [ "$#" -gt 0 ]; do
+    case "$1" in
       -h | --help ) 
         usage
         exit 0
@@ -51,45 +51,45 @@ function handle_options {
 
 function hyprland_switcher {
   local __signed
-  case "$__switch_to" in
+  case "${__switch_to}" in
     prev ) __signed=true ;;
     next ) __signed=false ;;
   esac
 
-  if [ "$__flag_move" = true ]; then
-    hyprctl dispatch movetoworkspace "$($__signed && echo r-1 || echo r+1)"
+  if [ "${__flag_move}" = true ]; then
+    hyprctl dispatch movetoworkspace "$({ ${__signed} && echo r-1; } || echo r+1)"
   else
-    hyprctl dispatch workspace "$($__signed && echo r-1 || echo r+1)"
+    hyprctl dispatch workspace "$({ ${__signed} && echo r-1; } || echo r+1)"
   fi
 }
 
 function custom_switcher {
   local __next_workspace
-  case "$__switch_to" in
+  case "${__switch_to}" in
     prev ) 
-      __next_workspace="$([ "$__curr_workspace" = 1 ] && echo "$__max_hypr_workspaces" || echo "$((__curr_workspace - 1))")"
+      __next_workspace="$({ [ "${__curr_workspace}" = 1 ] && echo "${__max_hypr_workspaces}"; } || echo "$((__curr_workspace - 1))")"
       ;;
     next )
-      __next_workspace="$([ "$__curr_workspace" = "$__max_hypr_workspaces" ] && echo 1 || echo "$((__curr_workspace + 1))")"
+      __next_workspace="$({ [ "${__curr_workspace}" = "${__max_hypr_workspaces}" ] && echo 1; } || echo "$((__curr_workspace + 1))")"
       ;;
   esac
 
-  if "$__flag_move"; then
-    hyprctl dispatch movetoworkspace "$__next_workspace"
+  if "${__flag_move}"; then
+    hyprctl dispatch movetoworkspace "${__next_workspace}"
   else
-    hyprctl dispatch workspace "$__next_workspace"
+    hyprctl dispatch workspace "${__next_workspace}"
   fi
 }
 
 function main {
   handle_options "$@"
   
-  if [ "$__max_hypr_workspaces" -lt 0 ]; then
-    echo 'error: invalid value of $MAX_HYPR_WORKSPACES' >&2
+  if [ "${__max_hypr_workspaces}" -lt 0 ]; then
+    echo "error: invalid value of \$MAX_HYPR_WORKSPACES" >&2
     echo ''
-    echo '$MAX_HYPR_WORKSPACES must be an integer greater than or equal to 0'
+    echo "\$MAX_HYPR_WORKSPACES must be an integer greater than or equal to 0"
     exit 1
-  elif [ "$__max_hypr_workspaces" = 0 ]; then
+  elif [ "${__max_hypr_workspaces}" = 0 ]; then
     hyprland_switcher
   else
     custom_switcher
